on:
  push:
    branches:
      - main
name: 🚀 🚀 🚀  Deploy CV Achraf Sendid Online 
jobs:
  web-deploy:
    name: 🚀 🚀 🚀  Deploy cv
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files TO SERVER
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.APP_LIVE_HOST }}
        username: ${{ secrets.APP_LIVE_FTP_USERNAME }}
        password: ${{ secrets.APP_LIVE_FTP_PASS }}
        exclude: .git*
          - .git*/**
          - node_modules/**
          - node_modules/**/*
          - **/.ENV
          - **/.env
          - .DS_Store
          - error_log
          - **/var/**
          - **/vendor/**
          - .user.ini
          - **/error_log
          - *.zip
          - **_old
